@startuml librraray
class Person {
    -name: String
    -age: int
    +getName(): String
    +getAge(): int
}

class Student {
    -studentId: int
    +getStudentId(): int
}

Person <|-- Student
@enduml